### ISSUE TITLE
Is vocalizer.io the same tool as this?

### ISSUE THREAD

**Issue by impressivewebs** [atifazam/vocalizer#10]
I just found:

https://www.vocalizer.io/

Is that the same as what's in this repo? If it is, you might want to include a link to the website from the repo, and vice-versa. Thanks.

**Comment by renatonascalves** [comment]
No! The owner of this repo created the mentioned website later. I believe, based on the good feedback by this service/library.

**Comment by impressivewebs** [comment]
Oh.... So you're saying vocalizer.io is a completely different script? Nothing to do with yours?

**Comment by renatonascalves** [comment]
By the way, it is not mine! I'm not the owner or the developer of this script. I'll let the owner answer for himself to not allow more misunderstanding. And also, he is the only one who can answer concretely your questions, I'd only guess.

**Comment by atifazam** [comment]
@renatonascalves is correct, @impressivewebs. Sorry, it's a bit confusing :)

Yeah, I originally built this JS plugin which uses an API to fetch pronunciations. Some of the feedback from that was that certain names weren't included.

Then - I launched Vocalizer.io, which is a UI tool to make recording your name and added the Vocalizer button to your website a lot easier. Vocalizer.io is built on top of this script, except that it does not use the Nameshouts API.
