### ISSUE TITLE
Compound name option?

### ISSUE THREAD

**Issue by ricardozea** [atifazam/vocalizer#2]
Hello,

A few things:
1. Is there a way to have the script work with compound names? For example mine: `ricardo zea`.
2. Also, it would be nice to be able to select the language in which we want the name to be pronounced in. 
3. [In this Pen](http://codepen.io/ricardozea/pen/24768edb28b4c6841028dafd684ba0b2) you can test how the same name (mine in this case) is pronounced differently, with a different voice and a different tone. Is there a way to make the script use a specific tone and pronunciation? I assume that's something related to the language, but I'm not entirely sure.

Anyhow, this is a GREAT script, Thanks for sharing it :) :+1:

**Comment by atifazam** [comment]
1. You could do this but you would need to opt to use your own audio file, and implement like this: `<span class="vocalizer" data-source="path/to/file">ricardo zea</span>`
2. Yeah, I was working on adding that functionality. Basically adding a `data-language` attribute you could set, however, then you would have to check the Nameshouts API to see what languages are available for your name. I wanted to abstract things away from having to deal w/ Nameshouts.
3. Again, for this specific scenario, I would opt to using your own audio file. Nameshouts recordings unfortunately are not the best.

Stay tuned though, there will a much more flexible version of Vocalizer launching in the next month or so. Glad you like what's been done so far!

**Comment by ricardozea** [comment]
Sounds good, looking forward to the features.

Thanks for the information.
