### ISSUE TITLE
Add to cdnjs

### ISSUE THREAD

**Issue by schlessera** [atifazam/vocalizer#3]
I would be awesome if you could submit this library to cdnjs (https://cdnjs.com/) or a similar JavaScript library CDN, so that people can just enqueue the library from such a CDN instead of hosting it themselves.

Thanks for a useful but of code! :)

**Comment by atifazam** [comment]
Yeah, I've been meaning to do that. Thanks for reminding me :)

**Comment by atifazam** [comment]
Added it to CDNJS!

`https://cdnjs.cloudflare.com/ajax/libs/vocalizer/1.0.0/vocalizer.min.js`
