### ISSUE TITLE
Only works on local server

### ISSUE THREAD

**Issue by ghost** [atifazam/vocalizer#4]
Hi, i have been triying to make it work on my little site but it only works on my local wamp server why is that?

**Comment by atifazam** [comment]
Hm, strange. Can you send me your site w/ it implemented? What is the console error?

**Comment by ghost** [comment]
Silly mistake actually i had an error on the path of including the js file. Thank's for answering now it's working http://michaelorndoff.66ghz.com/

Cheers

**Comment by atifazam** [comment]
Nice! Glad you got it to work.

I'd recommend implementing like this as the icon looks a little off:

`<h1>Michael <span class="vocalizer" data-source="path/to/file">Orndoff</span></h1>`

**Comment by ghost** [comment]
Yeah! That's so much better thanks again bro
