### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by chriscoyier** [atifazam/vocalizer#6]
I tried making the exact demo in the screenshot:
http://codepen.io/chriscoyier/pen/XNmzga?editors=1000

Looks like 2 of them work and 2 of them don't. The two that don't still put the icon on the page, and throw an error:

![screen shot 2016-11-09 at 9 29 39 am](https://cloud.githubusercontent.com/assets/69156/20143575/0cbfe880-a65f-11e6-8702-742cf8696bf7.png)

Just a heads up! Awesome thing!

**Comment by atifazam** [comment]
Weird! Looking into it :)

**Comment by atifazam** [comment]
@chriscoyier Alright, figured it out -> http://codepen.io/atifazam/pen/RorKoB

## 

`<p>Hello! My name is <span class="vocalizer" data-source="auto">Admiral Akbar</span>.</p>`

**Should be:**
`<p>Hello! My name is Admiral<span class="vocalizer" data-source="auto">Akbar</span>.</p>`

## 

`<p>Can you say the name <span class="vocalizer" data-source="auto">Adhmed?</span></p>`

**Should be:**
`<p>Can you say the name <span class="vocalizer" data-source="auto">Ahmed?</span></p>`

## 

`Admiral Akbar` can't be found in the [NameShouts API](http://www.nameshouts.com), only `Akbar`.
`Adhmed` isn't a name currently in the NameShouts API, but `Ahmed` is.

Both those cases return an error. Another option would be to use your own recording and implement w/ `data-source='path/to/file'` option. You can also record and host w/ the web version ([vocalizer.io](https://www.vocalizer.io)) that I just put into beta.

Hope that helps! I should probably add some better fallback for when a name doesn't exist in the API.

**Comment by chriscoyier** [comment]
cool cool. I would think a decent plan of action would be:

1) Don't throw an error if name isn't found. Just do nothing? Maybe console.error() a note?
2) Don't insert a play button (if not found, or if source fails to load)

**Comment by atifazam** [comment]
Good call. I'll make those updates 👍🏾

**Comment by gurpreet-hanjra** [comment]
Hello @atifazam @chriscoyier I think it's good to notify, in a polite manner that recording does not exist and further action to search on nameshout site (like the way its on readme). Instead of leaving user confused 'What went wrong?'.

**Comment by gurpreet-hanjra** [comment]
And for slow connections, some sort of 'working...' indication, for people like me in India ;)

**Comment by atifazam** [comment]
`up-for-grabs` issue added [#15](https://github.com/atifazam/vocalizer/issues/15).
