### ISSUE TITLE
SVG for icon?

### ISSUE THREAD

**Issue by winkerVSbecks** [atifazam/vocalizer#9]
Thank you for building this. This is awesome!

Would you be open to using an SVG icon instead of loading a icon font library? It is a bit much to download an additional ~50kb of assets just to display one icon. Here is the SVG code for the actual material icon:

```
<svg width="24" height="24" viewBox="0 0 24 24" id="ic_volume_up_24px" x="120" y="192">
  <path d="M3 9v6h4l5 5V4L7 9H3zm13.5 3A4.5 4.5 0 0 0 14 7.97v8.05c1.48-.73 2.5-2.25 2.5-4.02zM14 3.23v2.06c2.89.86 5 3.54 5 6.71s-2.11 5.85-5 6.71v2.06c4.01-.91 7-4.49 7-8.77s-2.99-7.86-7-8.77z"/>
</svg>
```

I can submit a PR but, it seems the repo only has minified code.

**Comment by atifazam** [comment]
Good idea - I will implement this. Thanks for suggesting!

**Comment by atifazam** [comment]
@winkerVSbecks Actually, I remember why I didn't do this originally. It's because I'm adding the styling to a pseudo-element `:after` rather than inline.
